### PR TITLE
RE CrossHairPickData for VR

### PR DESCRIPTION
**Pull request by Nightfallstorm**
On hold until #16 goes in, this will go on top

### CODE REVIEW

**Comment by alandtse** [comment]
Is this ready to merge?

**Comment by Nightfallstorm** [comment]
It should be ready now, had to rebase and force push to remove the unnecessary commits

**Comment by Nightfallstorm** [comment]
Scratch that, I left a comment that should be removed.

**Comment by Nightfallstorm** [comment]
Ok now it is good to go

**Pull request merged**
