### PR TITLE
RE Work Related to Poached Bugs VR (Scrambled Bugs Remake for VR)

### PR DESCRIPTION
**Pull request by RafearTheModder**
This is some RE work that I had to do in order to make some patches in my WIP Poached Bugs VR mod work.

One thing of note though: I see there is a KEEP_FOR_RE macro that has started being used in CommonLibVR after I forked off to work on this. Do I need to add it to any of the files I have created before merging this pull request?

### CODE REVIEW

**Comment by alandtse** [comment]
Yes if you could. It let's us build a pdb that has all the structure. Otherwise, unused ones disappear. Nightfall uses them for ida. I haven't figured it out for ghidra yet though.

**Comment by alandtse** [comment]
Oh other thing to consider. If it's primarily SSE re, putting it in po3's fork is better. We actually pull from it regularly so we'll get it here pretty quick too.

**Comment by RafearTheModder** [comment]
I have added the KEEP_FOR_RE() macro call to the spots I think it is needed for this PR.

As for the RE work side of things, I have only thoroughly verified the classes I added in VR but I strongly suspect they are equally as valid for SSE as well. Should I cancel this out and make a PR with PO3 instead and let it flow through anyway, or do you think it should go directly to CommonLibVR here since I have only really used and confirmed the behavior of this RE work in VR?

I think I am fine with either way you would prefer to handle it.

**Comment by alandtse** [comment]
I think the identity of some of the structures may be useful to send back. The visitor may not exist in SSE anymore, but I don't think it necessarily hurts. I don't think they'd accept the KEEP_FOR_RE flag though but I could add it back once I merge it in.

@nightfallstorm, any thoughts on whether we should encourage SSE (particularly if the person didn't actually do the RE in SSE)?

**Comment by Nightfallstorm** [comment]
IMO, it is case by case. @RafearTheModder Does the two new classes have VTABLE entries, or otherwise anything that would be quick to lookup in SSE? If so, confirming their existence in SSE is enough to put it in SSE as-is since SE and VR are pretty close. If an SSE modder finds a difference, they can always PR the fixes and we can keep the VR version. 

For the RE'd member in `MiddleHighProcessData`, I feel that 100% should go in SSE since that also seems very, very likely to be the exact same in SSE.

**Comment by RafearTheModder** [comment]
@Nightfallstorm both of the classes added due in fact have VTABLE entries that are actually already in the CommonLib Offsets_VTABLE.h (VTABLE_BGSEntryPointFunctionDataSpellItem and VTABLE_FindMaxMagnitudeVisitor) with REL::IDs that are also already uncovered in both the SSE and VR address libraries (240901 and 257550, each with a confidence of 3).

Given that and the rest of this conversation, it sounds like I should transplant my changes over to a PO3/CommonLibSSE PR instead and let it flow through into CommonLibVR at some point from there. I will go ahead and close this PR and make a PR to PO3 when I get some more time later instead.

Thanks for the detailed explanations.

**Comment by alandtse** [comment]
Thanks. We do appreciate the contrib. I'm just concerned about the amount of forking we have in commonlib and try to minimize it to the extent we can.  Let me know once in po3 and then I can pull it in here. In fact just synced with the latest.

**Pull request closed without merging**
