### PR TITLE
RE PlayerCharacter

### PR DESCRIPTION
**Pull request by Nightfallstorm**
queuedWeaponAttachs is left as `unkD28` to prevent maintenance bloating the PR, but will be renamed appropriately in the future.

### CODE REVIEW

**Comment by alandtse** [comment]
Ok, I know you had a couple of PRs you're pushing up to po3 and me. Is there an order I should pull in to avoid weird conflicts?

**Comment by Nightfallstorm** [comment]
If you prefer, I can pull in from po3 as a new PR and fixup the conflicts myself. Otherwise, any changes that affect both repos will be pushed to po3 first

**Comment by alandtse** [comment]
Why don't you handle the pull from Po3 too then. If there's any weirdness from stuff outside your RE, let me know.

**Comment by Nightfallstorm** [comment]
Sounds good, I'll pull in from PO3 for the next PR and include the conflicting changes as well

**Comment by Nightfallstorm** [comment]
I'll close this PR to make a new one with po3 pulled in

**Pull request closed without merging**
